### ISSUE TITLE
actions 里应该选什么项目？

### ISSUE THREAD

**Issue by Girlex** [anduinnn/HiFiNi-Auto-CheckIn#38]
找不到跟随时间表的啊？？

**Comment by cshvin** [comment]
正常 运行了，之前 没有fork库没用，但是现在cookie都放变量里 也没签到是什么回事啊？？

**Comment by cshvin** [comment]
明白了，变量创建错了地方，那么请问cookie多个账号应该怎么折腾？是否是在变量里添加？

**Comment by cshvin** [comment]
感谢大佬 搞定了 还有什么好玩的自动签到？

**Comment by anduinnn** [comment]
目前只维护了这个项目.
